# -*- coding: utf-8 -*-
"""端口（抽象接口，见 docs/architecture.md §6）。

用 Protocol 描述核心需要的外部能力；适配器实现它们。
MVP 只立了单曲下载链路用到的端口，其余（TaskStore/RateLimiter/HookBus…）
待对应阶段再加。
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..domain import Track, Album, DownloadTask


@runtime_checkable
class Decoder(Protocol):
    """将平台返回的加密音频地址解码为可直接使用的 URL。"""
    def decode(self, encrypted_url: str) -> str: ...


@runtime_checkable
class SignProvider(Protocol):
    """生成受保护接口请求所需的 xm-sign（见 docs/architecture.md §7.1）。

    受保护接口（如 `/revision/track/v1/baseInfo`）要求请求头里带 `xm-sign`，
    形如 ``{cadd}&&{sid}``。该端口把"如何拿到 xm-sign"这一易变点隔离起来：

    - 默认实现 `PySignProvider`：纯 Python 复算 `du_web_sdk` 的签名算法
      （device_info → zlib → AES-ECB → 上报 hdaa.shuzilm.cn → cadd&&sid），
      不依赖浏览器、不依赖 CDP。
    - 兜底实现可由前端按需注入（如让页面内 `du_web_sdk` 自己签、或扩展拿到）。
    - 现状 MVP 之前 ChromeSource 走"让页面自己签名"，故未单独立实现；本端口
      为纯 HTTP / 扩展等替代路径预留接入点。

    实现应是**线程安全**或且**外部同步**使用（同步方法、内部自行加锁或每次返回新值）。
    `sign()` 返回的字符串在平台侧有有效期，实现可自带缓存（见 PySignProvider）。
    """
    def open(self) -> None: ...
    def close(self) -> None: ...
    def sign(self) -> str: ...


@runtime_checkable
class Source(Protocol):
    """音源：获取单曲与专辑（后续扩展搜索）。"""
    def get_track(self, track_id: str) -> Track: ...
    def get_album(self, album_id: str) -> Album: ...

    # 批量会话：open/close 之间复用同一底层连接（如长驻浏览器），
    # 避免逐曲重复建链。无状态实现可空实现。
    def open(self) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class MediaSink(Protocol):
    """输出：把 URL 落盘（含进度回报、原子落盘）。"""
    def write(self, url: str, target_path: str, reporter: "ProgressReporter",
              cancel=None, progress_sink=None, expected_total: int = 0) -> None: ...


@runtime_checkable
class TaskStore(Protocol):
    """任务与专辑同步状态的持久化（含断点与增量游标）。"""
    def upsert_pending(self, tasks: list[DownloadTask]) -> list[DownloadTask]: ...
    def mark_downloading(self, task_id: int) -> None: ...
    def mark_done(self, task_id: int, target_path: str) -> None: ...
    def mark_failed(self, task_id: int, category: str, msg: str,
                    retryable: bool) -> None: ...
    def record_progress(self, task_id: int, bytes_done: int, total: int) -> None: ...
    def requeue_stale(self) -> int: ...
    def requeue_retryable_failed(self) -> int: ...
    def pending_albums(self) -> list[tuple[str, str, int]]: ...
    def pending_tasks(self, album_id: str) -> list[DownloadTask]: ...
    def all_tasks(self) -> list[DownloadTask]: ...
    def save_album_meta(self, album_id: str, title: str, total: int) -> None: ...
    def save_album_cursor(self, album_id: str, cursor: str) -> None: ...
    def album_cursor(self, album_id: str) -> str: ...
    def album_total(self, album_id: str) -> int: ...
    def close(self) -> None: ...


@runtime_checkable
class ProgressReporter(Protocol):
    """向前端回报进度（由前端实现）。"""
    def start(self, title: str, total: int) -> None: ...
    def update(self, done: int, total: int) -> None: ...
    def finish(self, path: str) -> None: ...
    def note(self, msg: str) -> None: ...      # 批量场景的逐条说明（专辑进度/跳过/失败等）
